# Generated by Django 5.2.1 on 2025-06-10 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('age', models.IntegerField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('data_arrived', models.DateField(auto_now_add=True)),
                ('sterilized', models.BooleanField(default=True, verbose_name='sterilized')),
                ('vaccinated', models.BooleanField(default=True, verbose_name='vaccinated')),
                ('special_needs', models.TextField(blank=True, verbose_name='special needs')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='location')),
            ],
            options={
                'verbose_name': 'animal',
                'ordering': ['-data_arrived'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LLooking for home', 'Looking For Home'), ('SNeed special care', 'Need Special Care'), ('HFound home', 'Found Home')], default='LLooking for home', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Wool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SShort', 'Short'), ('LLong', 'Long'), ('CCurly', 'Curly'), ('HHairless', 'Hairless')], default='SShort', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('phone', models.CharField(max_length=30, verbose_name='phone')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='new', max_length=20)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_request', to='main.animal')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'animal_breed',
                'verbose_name_plural': 'animal_breeds',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='main_animal_name_07d1b4_idx')],
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_breed', to='main.animalbreed', verbose_name='animal breed'),
        ),
        migrations.AddField(
            model_name='animal',
            name='color',
            field=models.ManyToManyField(related_name='animal_color', to='main.color', verbose_name='animal color'),
        ),
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_gender', to='main.gender', verbose_name='animal gender'),
        ),
        migrations.AddField(
            model_name='animal',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_size', to='main.size', verbose_name='animal size'),
        ),
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_status', to='main.status', verbose_name='animal status'),
        ),
        migrations.AddField(
            model_name='animal',
            name='wool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_wool', to='main.wool', verbose_name='animal wool'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['name'], name='main_animal_name_40c7ea_idx'),
        ),
    ]
