# Generated by Django 5.2.1 on 2025-06-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sterilized',
            field=models.BooleanField(default=False, verbose_name='sterilized'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vaccinated',
            field=models.BooleanField(default=False, verbose_name='vaccinated'),
        ),
    ]
