# Generated by Django 5.2.3 on 2025-06-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_animal_sterilized_alter_animal_vaccinated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('phone', models.CharField(max_length=30, verbose_name='phone')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='new', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('L', 'Looking for home'), ('S', 'Need special care'), ('H', 'Found home')], default='L', max_length=18),
        ),
        migrations.AlterField(
            model_name='wool',
            name='name',
            field=models.CharField(choices=[('S', 'Short'), ('L', 'Long'), ('C', 'Curly'), ('H', 'Hairless')], default='S', max_length=9),
        ),
    ]
