# Generated by Django 5.2.3 on 2025-06-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_volunteer_alter_animal_age_alter_status_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='volunteer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='volunteers/'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='new', max_length=20),
        ),
    ]
